### ISSUE TITLE
Type-safe custom scalars (e.g. JSONB)

### ISSUE THREAD

**Issue by spion** [typed-graphql-builder/typed-graphql-builder#32]
JSON objects in GraphQL are typically implemented as custom scalars.

It would be good if typed-graphql-builder had a type-safe way of dealing with them

Idea for consideration:

- Add `--generic-scalar` option.

If you write `--generic-scalar jsonb`, TGB will insert

```typescript
import {jsonb} from './scalars'
```

In addition, any time there is a `jsonb` output type field in the schema, instead of considering it to be a string, it will output the type:

```typescript
class OutputType {
  jsonField: Field<'jsonField', jsonb<'OutputType.jsonField'>, ...>
}
```

This allows you to implement jsonb in `./scalars.ts` however you like. You could, for example, default to `unknown`

```typescript
type jsonb<X> = unknown
```

Then you could add definitions for known scalars as you go

```typescript
type jsonb<X> = X extends 'OutputType.jsonField' ? MyJsonFieldType : unknown
```

We can extend this system with `--namespaced-scalars` and `--normal-scalar`

Namespaced generates

```typescript
class OutputType {
  jsonField: Field<'jsonField', jsonb.OutputType.jsonField, ...>
}
```

while `--normal-scalar` simply generates

```typescript
class OutputType {
  jsonField: Field<'jsonField', jsonb, ...>
}
```

(Not so great for jsonb, but useful for scalars that aren't that heterogenous)

**Comment by ilijaNL** [comment]
Some thoughts on this issue:
- Perhaps we should follow the graphql-codegen specification for defining the scalars (as a map)
- This should be also configured for inputTypes

**Comment by spion** [comment]
@ilijaNL I'm trying to figure out how it would look as a workaround for Hasura's lack of custom JSON scalars.

- https://github.com/hasura/graphql-engine/issues/3451#issuecomment-1266245636

With a bit of correction on that, we would get:

#### schema-overrides.graphql
```graphql
scalar MyJSONOverride

type MyOutputType {
  myScalar: MyJSONOverride
}
```

#### config.yaml
```yaml
schema:
  - schema-overrides.graphql
  - http://localhost:8080/v1/graphql: 
      headers:
        x-hasura-admin-secret: adminpassword 
config:
  ignoreFieldConflicts: true 
generates:
  ./api.s
    plugins:
    - typed-graphql-builder:
      scalars: 
        MyJSONOverride: ./path/to/scalars.ts#MyJSONOverride
```

I suppose that's a valid way to go.

Mapping this onto typed-graphql-buider it looks like we need

1) An exported API function that takes a single schema's AST
2) The options object shold take a KV map for scalars conforming to the convention `ScalarName: ./path#ExportName`
